/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedInvestimentosRouteImport } from './routes/_authenticated/investimentos'
import { Route as AuthenticatedFaturaPdfRouteImport } from './routes/_authenticated/fatura-pdf'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContasRouteImport } from './routes/_authenticated/contas'
import { Route as AuthenticatedCartoesRouteImport } from './routes/_authenticated/cartoes'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInvestimentosRoute =
  AuthenticatedInvestimentosRouteImport.update({
    id: '/investimentos',
    path: '/investimentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFaturaPdfRoute = AuthenticatedFaturaPdfRouteImport.update({
  id: '/fatura-pdf',
  path: '/fatura-pdf',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContasRoute = AuthenticatedContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCartoesRoute = AuthenticatedCartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/cartoes': typeof AuthenticatedCartoesRoute
  '/contas': typeof AuthenticatedContasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fatura-pdf': typeof AuthenticatedFaturaPdfRoute
  '/investimentos': typeof AuthenticatedInvestimentosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/cartoes': typeof AuthenticatedCartoesRoute
  '/contas': typeof AuthenticatedContasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fatura-pdf': typeof AuthenticatedFaturaPdfRoute
  '/investimentos': typeof AuthenticatedInvestimentosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/cartoes': typeof AuthenticatedCartoesRoute
  '/_authenticated/contas': typeof AuthenticatedContasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fatura-pdf': typeof AuthenticatedFaturaPdfRoute
  '/_authenticated/investimentos': typeof AuthenticatedInvestimentosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/cartoes'
    | '/contas'
    | '/dashboard'
    | '/fatura-pdf'
    | '/investimentos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/cartoes'
    | '/contas'
    | '/dashboard'
    | '/fatura-pdf'
    | '/investimentos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/cartoes'
    | '/_authenticated/contas'
    | '/_authenticated/dashboard'
    | '/_authenticated/fatura-pdf'
    | '/_authenticated/investimentos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/investimentos': {
      id: '/_authenticated/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof AuthenticatedInvestimentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fatura-pdf': {
      id: '/_authenticated/fatura-pdf'
      path: '/fatura-pdf'
      fullPath: '/fatura-pdf'
      preLoaderRoute: typeof AuthenticatedFaturaPdfRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contas': {
      id: '/_authenticated/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof AuthenticatedContasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cartoes': {
      id: '/_authenticated/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof AuthenticatedCartoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCartoesRoute: typeof AuthenticatedCartoesRoute
  AuthenticatedContasRoute: typeof AuthenticatedContasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFaturaPdfRoute: typeof AuthenticatedFaturaPdfRoute
  AuthenticatedInvestimentosRoute: typeof AuthenticatedInvestimentosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCartoesRoute: AuthenticatedCartoesRoute,
  AuthenticatedContasRoute: AuthenticatedContasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFaturaPdfRoute: AuthenticatedFaturaPdfRoute,
  AuthenticatedInvestimentosRoute: AuthenticatedInvestimentosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
